## 🔹 ##Kubernetes — Rolling Update Strategy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathnex-rolling
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    selector:
      matchLabels:
        app: roll
    template:
      metadata:
        Labels:
          app: roll
      spec:
        containers:
          - name: web
            image: nginx
